// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/user_definition.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserDefinition with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserDefinition with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserDefinitionMultiError,
// or nil if none found.
func (m *UserDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *UserDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Identifier

	// no validation rules for Role

	// no validation rules for Properties

	if len(errors) > 0 {
		return UserDefinitionMultiError(errors)
	}

	return nil
}

// UserDefinitionMultiError is an error wrapping multiple validation errors
// returned by UserDefinition.ValidateAll() if the designated constraints
// aren't met.
type UserDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDefinitionMultiError) AllErrors() []error { return m }

// UserDefinitionValidationError is the validation error returned by
// UserDefinition.Validate if the designated constraints aren't met.
type UserDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDefinitionValidationError) ErrorName() string { return "UserDefinitionValidationError" }

// Error satisfies the builtin error interface
func (e UserDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDefinitionValidationError{}
